### ISSUE TITLE
为何嵌入的html code无法得到渲染？

### ISSUE THREAD

**Issue by luckypoem** [LoeiFy/Mirror#10]
你好。
根据你的repo,我搭建了一个博客：http://mr.bright.biz.st/ ,不过某个嵌入了html code的帖子http://mr.bright.biz.st/#4 ，为何嵌入的html code无法得到渲染？
如何解决？

看到基于mirror的另一个项目https://github.com/JimmehCai/Journey，我根据它，也搭建了一个博客：
http://jn.bright.biz.st/ ，而该博客里的嵌入了html code的帖子：http://jn.bright.biz.st/#4 ，其嵌入的html code却得到了渲染，为何它的行，你的却不行呢？

**Comment by LoeiFy** [comment]
@luckypoem 

之前是程序是获取 issue 的原始 md 数据再解析，而现在的是直接使用 GitHub 解析过的 html 数据，所以现在网页展示内容完全跟 GitHub isuue 上的是一样的。

你的 issue https://github.com/luckypoem/Mirror/issues/4 并没有解析 html code，所以网页也不会解析

如果你需要插入 video，可以参考一下这个

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos
