### ISSUE TITLE
task list 渲染可能有问题

### ISSUE THREAD

**Issue by Haagaau22** [LoeiFy/Mirror#11]
你好，[issue](https://github.com/Zonzely/Recordum/issues/1)里面task list 可以被渲染，但是生成的[网页](https://zonzely.github.io/blog/#1)，没有正常显示。

**Comment by LoeiFy** [comment]
@Zonzely 
`task list` 已经解析出来了，但是我 css 样式把 `input` 默认给隐藏了，等一会会提交一个版本，修复这个问题

**Comment by LoeiFy** [comment]
@Zonzely v0.3.3 修复这个问题了

**Comment by Haagaau22** [comment]
@LoeiFy  我upgrade后，push gh-pages, 好像还是没有生效， 谢谢啦

**Comment by LoeiFy** [comment]
@Zonzely 
你没有更新成功，最新版本的 js hash 是 `build.839e9662f300cd518c7b.js`
但你的页面还是 `build.8a23aa17e54fde985f1d.js`

**Comment by Haagaau22** [comment]
@LoeiFy 我把Mirror 卸载了，用npm重装， 生成的js 还是`build.8a23aa17e54fde985f1d.js`, 可能用npm装的还是旧的。
不过 我直接把你的`build.839e9662f300cd518c7b.js`下载下来，然后修改index.html，就可以正常显示了。
thank you

**Comment by LoeiFy** [comment]
@Zonzely sorry，我才发现我没有 publish 新的版本
