### ISSUE TITLE
Feature: Option to load comments automatically?

### ISSUE THREAD

**Issue by mii9000** [LoeiFy/Mirror#13]
Give the user an option to configure whether comments are loaded automatically or not shown until "View Comments" is clicked (the default).

**Comment by LoeiFy** [comment]
@Ibrahim-Islam 

the feature can be done, just trigger the button be clicked when scroll bottom 

and we can also use `disqus` instead of `issue` comment system

btw, about the option key name, do you have any idea ?

**Comment by mii9000** [comment]
On second thought, I think its best to just load the comments asynchronously when an issue/article loads up and have something like `comment_limit` that will fetch comments in batches when clicked `View More` if github comments. Otherwise, user can opt for services like Disqus or something else.

**Comment by LoeiFy** [comment]
i see, and i will add the feature a bit later. 
thanks for the advice, and the pr are welcomed :)

**Comment by mii9000** [comment]
Sure. I will try to work on it then.
