### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by demoleo** [LoeiFy/Mirror#14]
4.0版本的几个问题：
1、Label 只在首页显示而在blog单页中不显示？
2、为什么我的顶部主页小图标的链接重复显示我的主页地址？ worz.net/worz.net 这样。
3、有可能调整字体大小么？现在的正文字体太小了，还是说抓取 issues 内容只能是缺省的大小？

**Comment by LoeiFy** [comment]
@demoleo 
1. v0.4.0 去掉了 label 显示
2. 你在你的资料设置个人网站那里加上 `http://` 前缀
3. 字体大小是可以调整的，你可以按自己需要修改，重新生成一份
https://github.com/LoeiFy/Mirror/blob/master/src/index.scss#L307

**Comment by demoleo** [comment]
啊，label去掉还是蛮可惜的啊，觉得还挺有用的呢，或者做成开关式选项可以么？

**Comment by demoleo** [comment]
还是要请教，程序小白，我按自己需要修改的css，具体的操作过程是怎么样的呢？谢谢了。

**Comment by LoeiFy** [comment]
如果你要自定义多方面的，那你就要 clone 一份到本地，先确认安装了 `node`，接着：

```bash
# 安装相关包
npm install

# 运行，访问 127.0.0.1:8080 就可以看到页面，你可以修改 src/config.js 定义显示内容
npm run dev 

# 生成最终文件，最后生成的 zip 包就是你修改后的
npm run build
```

主体 css 的修改是 `src/index.scss`，模版修改的是 `src/template.js`

**Comment by demoleo** [comment]
是把自己生成的 zip 包的内容直接 push 到我的 github 就可以了么？我试了好多次，总是不行，显示 Something went wrong, please checkout the configurations

**Comment by demoleo** [comment]
已经搞定了，犯了些低级错误，谢谢 LoeiFy 的耐心，这个 issue 可以 close 了。

**Comment by LoeiFy** [comment]
@demoleo 不客气
