### ISSUE TITLE
markdown 可以添加支持[TOC]吗

### ISSUE THREAD

**Issue by Haagaau22** [LoeiFy/Mirror#15]
您好, github好像不支持TOC, 可以添加支持TOC吗

**Comment by LoeiFy** [comment]
@Zonzely 由于并没有用到 md 渲染插件，直接使用了 github api 提供的生成 html，GitHub 也并没有提供 TOC，所以这个只能 js 后期生成，但并没有考虑好要把 toc 放在页面哪个地方，所以让我先看看放在哪里好，当然你可以自己添加上去或者提供建议

**Comment by Haagaau22** [comment]
@LoeiFy thank you
