### ISSUE TITLE
Posts are not being populated

### ISSUE THREAD

**Issue by mii9000** [LoeiFy/Mirror#16]
Check it out at: http://ibrahim-islam.github.io
Issues request gets through and are returned successfully.
No js errors in console either.

**Comment by LoeiFy** [comment]
because of the config

your `user` is `ibrahim-islam`but the issues author name is `Ibrahim Islam`. ( the `i` and `I` )

the problem has been fixed, you can upgrade or just change the `user` to `Ibrahim Islam`
