### ISSUE TITLE
Wrong ordering in terms of date displayed

### ISSUE THREAD

**Issue by mii9000** [LoeiFy/Mirror#17]
The order of the posts in terms of date seems a bit odd at first glance : http://ibrahim-islam.github.io
Because `updated_at` is displayed but the order of results returned and shown on the view is ordered by `created_at`. Either `created_at` needs to be displayed or results need to be sorted according to `updated_at`. @LoeiFy Let me know which one you decide and I can do a PR.

**Comment by LoeiFy** [comment]
yep, the `update_at` is the issue lasted update time, but the post list is ordered by `created_at`.  

in normal conditions, when the user update the issue contents, i think the post of the updated issue should be ranked first, and others can see the new contents easily

so i would prefer the posts list be sorted by `updated_at`

**Comment by mii9000** [comment]
Ok. I will look into making that change.
