### ISSUE TITLE
Something went wrong, please checkout the configurations

### ISSUE THREAD

**Issue by wxiubin** [LoeiFy/Mirror#20]
<img width="1203" alt="error" src="https://cloud.githubusercontent.com/assets/16896889/25940059/775076b8-3667-11e7-8b7e-b477210312ce.png">

**Comment by LoeiFy** [comment]
@sanyucz 这个是拉回数据时候未完成，或者完成后操作出错了。很大可能是请求数据出错了，看看你的控制台的 `network` 还有 `console` 有什么错误
