### ISSUE TITLE
Feature: 添加显示label

### ISSUE THREAD

**Issue by dzhai** [LoeiFy/Mirror#22]
自己简单扩展了下，感觉代码扩展好麻烦
点击按钮可以显示所有的label，点击label显示对应的issue

**Comment by LoeiFy** [comment]
@dzhai 原来版本就有这个功能的，只是我后面觉得多余去掉了

https://github.com/LoeiFy/Mirror/commit/d747c1206485bcdff9c34990550b72bb7cc7e465#diff-eed64a56d9b95461323a66cae6d2380bL106

**Comment by dzhai** [comment]
恩，回头研究下

**Comment by LoeiFy** [comment]
@dzhai 新版本已经添加 labels 功能
