### ISSUE TITLE
不能保持token

### ISSUE THREAD

**Issue by yangweijie** [LoeiFy/Mirror#24]
不知道为什么 我的账号自己生成一个token 之后 ，填入index.html  访问后就报401 然后去setting 里看 token 就消失了。提示要应用授权，不知道如何是好。

**Comment by yangweijie** [comment]
解决了， 原来是GitHub 不允许公开的库 直接提交任何 有效token 字符串，因此 我把字符串拆解为数组，配置里 join 避开了检测 var t_arr = ['44c1', '25202eb7', 'e68181187b22c', 'XXXXXXXXXXXX']

**Comment by LoeiFy** [comment]
wiki 上已经说明 token 需要分割的

```yml
# token 设置
# token 必须以 '#' 分割
# 如果你的 token 是 5c31bffc137f44faf7efc4a84da827g7ca2cfeaa 
# 那么这里填入的值为 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:

```
