### ISSUE TITLE
About loading animation

### ISSUE THREAD

**Issue by Eronana** [LoeiFy/Mirror#25]
I think loading bar on top like Github is better.
![image](https://user-images.githubusercontent.com/9164153/28148387-fcacbbc8-67b8-11e7-8e5e-9d920cdea079.png)

I have read the source, I think we can left current loading as a alone animation that only used in first load, and make `#loading` be the new top loading bar that like Github.

PS: My English is bad, can I use Chinese directly here?

**Comment by LoeiFy** [comment]
@Eronana :)

跳转时候的 loading 效果有一个遮罩层，防止没有加载完成就再次被点击，所以我把 ajax 的请求多次判断也去掉了。

如果换成类似 GitHub 的加载效果，那么也是要加一个透明层，这样也是点击不了其他地方，用户觉得奇怪（加了半透明层，用户就知道加载中，点不了，因为挡住了）

如果头部加载效果再加上半透明层，这样也不好看，因为不能让用户很明显知道在加载中。并且跟现在页面顶部有一个黑色条设计冲突

所以综合起来，我选择现在的加载设计。不过你也可以自己定制，具体调用 loading 效果就一个地方 
https://github.com/LoeiFy/Mirror/blob/master/src/api/fetcher.js#L24

**Comment by Eronana** [comment]
呃 你这个说的很有道理
但是 点进文章时，突然被半透明的遮罩挡住，这种不连续的用户体验不是很爽啊。

如果自己改一下的话，需要处理好多次点击造成的多次请求，以及顶部的进度条要和现有的设计兼容且和谐
是这样吧

**Comment by LoeiFy** [comment]
是的，差不多就是这两点
