### ISSUE TITLE
organization 的blog怎么配置token

### ISSUE THREAD

**Issue by Pines-Cheng** [LoeiFy/Mirror#28]
organization的blog项目，同样是在issue里面写blog，怎样获取用户名和token？

**Comment by LoeiFy** [comment]
一样可以使用个人 `token`，不过要配置一下，添加读取 `organization ` 权限

不过这边的 API 也要修改一下，等我更新一个版本

**Comment by LoeiFy** [comment]
@Pines-Cheng 已经支持 organization 项目

**Comment by Pines-Cheng** [comment]
666

**Comment by Pines-Cheng** [comment]
已试验，发现两个问题：
- organization的blog默认为空，因为默认author为组织名，如果不配置author，则获取到的文章会被filter函数过滤掉。
- organization获取的文字不是按时间排序的，这个应该是和github的接口有关。

**Comment by LoeiFy** [comment]
是需要设置 `authors`，另外排序是按照更新时间来排序的，不是按照创建时间，不过没有加上配置，加上的话觉得太多配置了
