### ISSUE TITLE
build.xxxx.js 404

### ISSUE THREAD

**Issue by Haagaau22** [LoeiFy/Mirror#30]
您好， 我从npm安装最新的mirror, 生成的`index.html`中访问`build.xxx.js`的路径是 `/build.xxx.js`。
我的项目名是blog, 访问`https://zonzely.github.io/blog`时， 会报`build.xxx.js`404， 我把`index.html`中的路径改成`/blog/build.xxx.js`就可以访问正常了。
另外， 新版本的mirror, 好像不能右键新标签打开文章了.
谢谢

**Comment by LoeiFy** [comment]
是因为你的 blog 是在二级路径，所以路径引用错了，迟点会修复这个问题。另外也会在下个版本加回新页面打开文章功能

**Comment by LoeiFy** [comment]
@Zonzely fixed
