### ISSUE TITLE
关于 Mirror 的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [LoeiFy/Mirror#31]
按照 http://mirror.am0200.com/#/posts/11 的描述配置完后，发现出现如下错误：

![image](https://user-images.githubusercontent.com/81074/30355922-e0b19876-97fb-11e7-84ff-06d119e41e17.png)

估计是 token 有问题？我申请的 token 如下：

`ef3bb921d1efccxxxxxx535ad0319d889c66d197` ，按照描述 用 # 分割，

> token: #ef3bb921d1efccxxxxxx535ad0319d889c66d197

但不清楚为什么例子给出的内容：

> 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa

#号前多了个5 ，不清楚是什么意思？不知道是否是因为这个问题导致？

**Comment by LoeiFy** [comment]
不好意思说的不太明白，意思是当你的 token 为
`sah5656asdjkasdj` 时候，
添加上去应该是 `s#ah5656asdjkasdj`

就是在 token 字符串中间加一个 # 号，任何位置都可以，但是不能首尾加

**Comment by Kenshin** [comment]
额，搞定了~ 估计是我没理解的问题，因为没有其他人问这个问题... 👏  👍 😣  😢  😂

PS：希望以后加入 `点击 tag/label 后不用跳到 github issues 页面` ，而是在 mirror 的页面上。
