### ISSUE TITLE
关于 favicon 不显示的问题

### ISSUE THREAD

**Issue by marsxxl** [LoeiFy/Mirror#34]
请问，按照教程搭好了博客，只是 favicon 不显示，是空白的，这个要怎么解决呢，更换文件夹内的`favicon.ico`文件，重新 push 上来吗？

**Comment by LoeiFy** [comment]
你修改一下你的 gh-pages 分支下的 index.html，把 `/favicon.ico` 改成 `favicon.ico`

**Comment by marsxxl** [comment]
谢谢，我自己没注意路径😂
