### ISSUE TITLE
Token 建立后被删除

### ISSUE THREAD

**Issue by geekrainy** [LoeiFy/Mirror#37]
建立一个 token 后，很快发现 token 被删除，Github 发来了安全警示邮件：
>We noticed that a valid OAuth access token of yours was committed to a public GitHub repository. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.
>
>As a precautionary measure, we have revoked the OAuth token. A new token will need to be generated in order to continue using OAuth to authenticate to GitHub. Here are a couple of steps you can do to ensure your account security has not been compromised:

**Comment by LoeiFy** [comment]
所以才有 token 用 ‘#’ 号分割的要求

```yml
# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:
```

**Comment by geekrainy** [comment]
这样子啊，学习了，感谢答疑！: )
