### ISSUE TITLE
[Feature Request]能否添加更多的文章排序方式?

### ISSUE THREAD

**Issue by MadIcecream** [LoeiFy/Mirror#38]
现在只支持按issue的发布或更新时间来排序，实际整理博文还是有些僵硬。
能不能像hugo那样，支持在issue头部手动添加时间？

**Comment by LoeiFy** [comment]
1. 有这样需求的人比较少
2. 实现起来有些麻烦：列表拉取的数据并没有正文的数据，所以需要二次取到正文数据才可以知道定义时间

**Comment by MadIcecream** [comment]
可以考虑在issue的标题中添加额外数据，例如“博文名称[time=2017-12-24 08:00+8]”，这样解析时如果发现了存在额外数据，就以添加的为准。

我确实是需要这样的功能的，如果官方没有打算加，我可以自己实现，只是希望能为我提供一点实现思路 :)

**Comment by LoeiFy** [comment]
在标题处加标记是一个办法，还有一个就是把正文内容首次就拿到

https://github.com/LoeiFy/Mirror/blob/master/src/api/issues.js#L28-L58

在 updatedAt 上面加上 bodyHTML，这样你就可以首次就获得正文数据，后续打开文章页也不需要再次拉取数据了，缺点是首次加载内容会多一些
