### ISSUE TITLE
文章列表页面的时间戳问题

### ISSUE THREAD

**Issue by WyattJia** [LoeiFy/Mirror#39]
你好，感谢你的贡献，你的博客系统十分优雅，我一直有在使用。但是期间遇到一个疑问，文章列表页面的时间戳貌似是根据 issue 的更新时间来就决定的，请问能不能改成 issue 的创建时间呢？因为我有时候回 review 自己的 blog issue ，可能会在同一天对许多博客都做了更改，这样在文章列表上的时间都变成同一天了，窃以为这样有点不雅观。
感谢你阅读我的 issue 。

**Comment by LoeiFy** [comment]
你可以直接在 `config.yml` 设置的，或者在 `index.html` 添加设置。[具体文档](https://github.com/LoeiFy/Mirror/wiki/%E4%B8%AD%E6%96%87%E6%95%99%E7%A8%8B#%E9%85%8D%E7%BD%AE%E4%BD%A0%E7%9A%84%E5%8D%9A%E5%AE%A2)

```yml
# 文章排序，依据更新时间还是创建时间
# 值为 'UPDATED_AT' 或者 'CREATED_AT'
order: 'UPDATED_AT'
```

**Comment by WyattJia** [comment]
@LoeiFy 多谢解答

**Comment by WyattJia** [comment]
@LoeiFy 你好，我用新版的 mirror 生成页面之后发现无法翻页了。开发者工具提示 `index.js:144 Uncaught TypeError: S.go is not a function`

``` javascript
index.js:144 Uncaught TypeError: S.go is not a function
    at n.S.notFound [as page404] (index.js:144)
    at n.value (index.js:26)
    at index.js:16
S.notFound @ index.js:144
value @ index.js:26
(anonymous) @ index.js:16
```

node 版本为 `v9.6.0` 和 `v6.9.1` 
npm 版本是 `5.6.0`
页面地址：http://blog.bitstring.xyz/
仓库地址: https://github.com/wellls/blog/commits/gh-pages

是否能抽空帮我看一下？非常感谢！！

**Comment by LoeiFy** [comment]
@wellls router 有 bug，这边会处理一下

**Comment by LoeiFy** [comment]
@wellls 已经修复，重新安装到 1.3.3 即可

**Comment by WyattJia** [comment]
@LoeiFy 非常感谢
