### ISSUE TITLE
请教一个问题：在markdown 中书写的 iframe 没有渲染

### ISSUE THREAD

**Issue by ly525** [LoeiFy/Mirror#41]
您好，请教一个问题：在markdown 中书写的 iframe 没有渲染，这是由于哪方面做了限制吗？还是有其他方面的考虑？
1. markdown 地址：https://github.com/ly525/blog/issues/72
2. 渲染文档地址：https://ly525.github.io/blog/#/posts/72

非常感谢

**Comment by LoeiFy** [comment]
@ly525 这个 markdown 渲染是由 github 提供的渲染，所以你在原始 issue 上看到的是怎样的效果，那么你博客上的效果也是一样的。因为现在你的 iframe 在 issue 上也是没有被渲染的，所以博客也一样

你可以查看一下怎么在 issue 上插入 jsfiddle 之类的

**Comment by ly525** [comment]
好的，理解了。非常感谢。
