### ISSUE TITLE
today, I open my GitHub.io get the error?

### ISSUE THREAD

**Issue by labike** [LoeiFy/Mirror#43]
![error](http://oo8hp4ueg.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-06-05%20%E4%B8%8B%E5%8D%889.40.27.png)

what's mean and the error?

**Comment by LoeiFy** [comment]
@labike token 错误

**Comment by labike** [comment]
@LoeiFy 直接修改不了token,是不是要重新部署一次github.io
