### ISSUE TITLE
部署完成后打开网页一直Loading

### ISSUE THREAD

**Issue by WingLim** [LoeiFy/Mirror#44]
开F12看了看，报错是这个：
![bug](https://user-images.githubusercontent.com/6434137/42559242-2b050896-8526-11e8-8f33-46bd2144d8d1.png)

**Comment by WingLim** [comment]
congfig.xml已经设置好了。

**Comment by LoeiFy** [comment]
还有最后一步你没有运行 `mirror build`

**Comment by WingLim** [comment]
吖，好了，没有仔细看说明。
