### ISSUE TITLE
How to add comment for blog?

### ISSUE THREAD

**Issue by labike** [LoeiFy/Mirror#45]
How to add comment for blog? I try to fitment and Disqus but not used! so I want to your blog how to add comment? thank you very much!

**Comment by LoeiFy** [comment]
现在是直接使用 issue 的 comment 的，用户要评论需要到 github 上，如果要加自定义评论，会有点麻烦。你可以看这个地方自行添加

https://github.com/LoeiFy/Mirror/blob/master/src/template/comments.js#L37-L66
