### ISSUE TITLE
authors问题

### ISSUE THREAD

**Issue by 1715173329** [LoeiFy/Mirror#50]
配置中的authors在index.html中会被不加双引号地使用，导致界面一直处于Loading状态。
实测需要加上双引号之后才能正常访问（我这边是这个情况）

原配置：
`"authors":1715173329`
实际应是
`"authors":"1715173329"`

**Comment by LoeiFy** [comment]
是的，必须是字符串，因为要处理多用户问题，具体代码是这里
https://github.com/LoeiFy/Mirror/blob/master/src/template/filter.js#L11

**Comment by 1715173329** [comment]
好的，谢谢。
