### ISSUE TITLE
Proxy替换Observer该如何实现呢？

### ISSUE THREAD

**Issue by labike** [LoeiFy/Mirror#52]
现在源码中用的是Observer, 创建实例的时候传入了mirror这个对象, 然后还有个watch监听方法, 如果换成Proxy实现的话, 是不是应该是这样:
```
let handler  = {
    // Observer constructor()
    get(){
        
    }
}
new Proxy(mirror, handler)
```
handler的get()方法是否相当于Observer的constructor()方法, 但是Proxy怎么实现像Observer的watch()方法呢?因为在程序入口处用了Observer的watch方法.
```
observer.watch({
    user: '',
    issues: '',
    issue: '',
    comments: ''
})
```
大佬有时间的话指点一下, 谢谢!!!

**Comment by LoeiFy** [comment]
差不多的，同样是 get set 方法触发一些动作。

不过我认为现在没必要这样做，基本的事件订阅就好了，当时写得太复杂太乱，其实没必要这样子
