### ISSUE TITLE
说下遇到的问题

### ISSUE THREAD

**Issue by letsoon** [LoeiFy/Mirror#54]
> ### windows系统下运行`npm run build`报错
![20200403182231](https://user-images.githubusercontent.com/16750352/78350795-5e145d00-75d8-11ea-8cb8-8b56380100aa.png)
> ### 然后尝试手动输入命令，并未生成打包目录和文件
![20200403182409](https://user-images.githubusercontent.com/16750352/78350985-aaf83380-75d8-11ea-8c4d-aecfc63b7c04.png)

**Comment by LoeiFy** [comment]
1. rm -rf 可能 window 下有问题
2. window 下 NODE_ENV 有问题，你可以将 `falco.config.js` 中的代码换一下

```js
// 原代码
mode: NODE_ENV ? 'production' : 'development',

// 改成
mode: 'production',
``` 

这两个问题都可以用相关 npm 模块解决

**Comment by letsoon** [comment]
谢谢，已解决
> 调整部分
```javascript
// falco.config.js
// 注释该行
//mode: NODE_ENV ? 'production' : 'development',
```
```javascript
// clean.js
const { removeSync } = require('fs-extra')
const path = require('path')
removeSync(path.resolve(__dirname, 'docs'))
```

```javascript
// package.json
  "scripts": {
    "start": "falco -d -c -m src/index.js",//增加-d参数设置成development模式
    "prebuild": "node ./clean.js",//运行脚本，使用fs-extra模块删除docs目录
    "build": "falco -c -o docs -m src/index.js",
    "postbuild": "node ./build.js",
    "lint": "eslint ."
  }
```
