### ISSUE TITLE
文章页下方会显示issue列表

### ISSUE THREAD

**Issue by leirock** [LoeiFy/Mirror#6]
在存在较多issue情况下，通过点击more posts加载了较长的文章列表之后，如果打开其中一篇篇幅较短的文章，页面下部add comments和页脚之间会显示一个不完整的文章列表，希望能够修复一下(用的是gh-pages上的版本)。情况如下图：
![default](https://cloud.githubusercontent.com/assets/19180725/21363139/507d75d2-c726-11e6-965e-5d8b8a99ea82.PNG)

**Comment by LoeiFy** [comment]
@dongleizhang 这个问题已经在 v0.1.3 修复，你重新安装或者下载 zip 进行相关文件替换即可

同时参考你的设置，将头部颜色换回之前版本的蓝黑颜色，以及添加了 labels 链接

**Comment by leirock** [comment]
@LoeiFy 谢谢及时回复，这个问题已经修复。然后可能新出现一个问题，就是现在在阅读完文章返回主页时候，滚动条不会回到之前的所在位置，而是跳到了最上面，这样对于阅读不是很方便，特别是阅读完早期文章之后想回到之前所在的文章列表位置变得很困难。这个问题是这次修改之前没有的，希望也能修复。O(∩_∩)O谢谢

**Comment by LoeiFy** [comment]
@dongleizhang 已经修复滚动这个问题，感谢你的反馈

**Comment by leirock** [comment]
@LoeiFy 也十分感谢你的及时回应！已经准备采用这个主题作为我的博客，哈哈
