### ISSUE TITLE
graphql接口调用问题

### ISSUE THREAD

**Issue by coderzhw** [LoeiFy/Mirror#60]
首先非常喜欢这款主题，但有个问题，博客会调用https://api.github.com/graphql这个接口获取数据，导致国内访问很慢，而且也没办法用第三方的静态资源加速服务来加速。有没有办法生成网站的时候直接把这些数据搞到静态页面里去？和hexo那种方式一样了？？https://github.com/xuya227939/LiuJiang-Blog这个也是用的issue做的博客，但不知道他怎么实现的。

**Comment by LoeiFy** [comment]
可以参考下这个 https://github.com/acyortjs
