### ISSUE TITLE
graghql 报 401 错误

### ISSUE THREAD

**Issue by XYZscratcher** [LoeiFy/Mirror#70]
![image](https://user-images.githubusercontent.com/108533817/206202462-073bf578-f0f8-4b66-9cad-743dfe4fbcde.png)

@LoeiFy

**Comment by XYZscratcher** [comment]
graghql 报 401 错误
token 好像根本没有用来查询，触发了速率限制

**Comment by way-zer** [comment]
这个encrypt貌似不兼容新版本的Github PAT
编解码后token不一致了

**Comment by XYZscratcher** [comment]
原来是自己的 hash 生成错了而已
