### ISSUE TITLE
Would it be better to add some Chinese fonts?

### ISSUE THREAD

**Issue by leirock** [LoeiFy/Mirror#8]
Hi LoeiFy,

I find this blog theme can not well support Chinese characters. In Windows rather than Mac OS, all Chinese characters will be shown in sans-serif which is not very beautiful. 

To optimize the display of Chinese characters both in Windows and Mac OS, I just add `PingFang SC` and `Microsoft YaHei` into the `font-family` both in article list page (frontpage) and content page of my blog as follows:

`font-family: apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, PingFang SC, Microsoft YaHei, sans-serif`

Hope the further version of Mirror can support Chinese characters better. Thanks!

Best,
Donglei

**Comment by LoeiFy** [comment]
@dongleizhang thanks, `v0.3.1` has added the font `microsoft-yahei`

**Comment by leirock** [comment]
@LoeiFy I notice that you just added `PingFang SC` and `Microsoft YaHei` into the `font-family` of article list page, but the article content pages still show `sans-serif` font for Chinese characters.

**Comment by LoeiFy** [comment]
@dongleizhang `v0.3.2` has been fixed
